/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author User
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Ag_ID = new javax.swing.JLabel();
        txt_Ag_ID = new javax.swing.JTextField();
        lbl_Ag_Cliente = new javax.swing.JLabel();
        lst_Ag_Cliente = new javax.swing.JComboBox<>();
        lbl_Ag_Servico = new javax.swing.JLabel();
        lst_Ag_Servico = new javax.swing.JComboBox<>();
        lbl_Ag_Valor = new javax.swing.JLabel();
        txt_Ag_Valor = new javax.swing.JTextField();
        lbl_Ag_Data = new javax.swing.JLabel();
        txt_Ag_Data = new javax.swing.JTextField();
        lbl_Ag_Hora = new javax.swing.JLabel();
        txt_Ag_Hora = new javax.swing.JTextField();
        lbl_Ag_Obs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Ag_Obs = new javax.swing.JTextArea();
        btn_Ag_Agendar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Agenda = new javax.swing.JTable();
        img_Ag_Painel = new javax.swing.JLabel();
        img_Ag_Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_Ag_ID.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_ID.setText("ID");
        getContentPane().add(lbl_Ag_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        txt_Ag_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Ag_IDActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Ag_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 170, 40));

        lbl_Ag_Cliente.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_Cliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_Cliente.setText("Cliente");
        getContentPane().add(lbl_Ag_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        lst_Ag_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Pedro", "Tiago", "João" }));
        lst_Ag_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lst_Ag_ClienteActionPerformed(evt);
            }
        });
        getContentPane().add(lst_Ag_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 170, 40));

        lbl_Ag_Servico.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_Servico.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_Servico.setText("Serviço");
        getContentPane().add(lbl_Ag_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        lst_Ag_Servico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Barba", "Cabelo", "Completo" }));
        getContentPane().add(lst_Ag_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 170, 40));

        lbl_Ag_Valor.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_Valor.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_Valor.setText("Valor (R$)");
        getContentPane().add(lbl_Ag_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        txt_Ag_Valor.setText("0");
        txt_Ag_Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Ag_ValorActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Ag_Valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 170, 40));

        lbl_Ag_Data.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_Data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_Data.setText("Data");
        getContentPane().add(lbl_Ag_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));
        getContentPane().add(txt_Ag_Data, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 40));

        lbl_Ag_Hora.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_Hora.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_Hora.setText("Hora");
        getContentPane().add(lbl_Ag_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, -1, -1));

        txt_Ag_Hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Ag_HoraActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Ag_Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 170, 40));

        lbl_Ag_Obs.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbl_Ag_Obs.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Ag_Obs.setText("Observação");
        getContentPane().add(lbl_Ag_Obs, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        txt_Ag_Obs.setColumns(20);
        txt_Ag_Obs.setRows(5);
        jScrollPane1.setViewportView(txt_Ag_Obs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 520, 320));

        btn_Ag_Agendar.setBackground(new java.awt.Color(0, 204, 102));
        btn_Ag_Agendar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ag_Agendar.setText("AGENDAR");
        btn_Ag_Agendar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btn_Ag_Agendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 520, 40));

        tbl_Agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Pedro", "Cabelo"},
                {"2", "Tiago", "Completo"},
                {"3", "João", "Barba"},
                {null, null, null}
            },
            new String [] {
                "ID", "CLIENTE", "SERVIÇO"
            }
        ));
        jScrollPane2.setViewportView(tbl_Agenda);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 1090, 360));

        img_Ag_Painel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(img_Ag_Painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        img_Ag_Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/images/AgendaFundo.png"))); // NOI18N
        getContentPane().add(img_Ag_Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Ag_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Ag_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Ag_IDActionPerformed

    private void lst_Ag_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lst_Ag_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lst_Ag_ClienteActionPerformed

    private void txt_Ag_ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Ag_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Ag_ValorActionPerformed

    private void txt_Ag_HoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Ag_HoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Ag_HoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create lbl_ID_Agenda form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ag_Agendar;
    private javax.swing.JLabel img_Ag_Fundo;
    private javax.swing.JLabel img_Ag_Painel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Ag_Cliente;
    private javax.swing.JLabel lbl_Ag_Data;
    private javax.swing.JLabel lbl_Ag_Hora;
    private javax.swing.JLabel lbl_Ag_ID;
    private javax.swing.JLabel lbl_Ag_Obs;
    private javax.swing.JLabel lbl_Ag_Servico;
    private javax.swing.JLabel lbl_Ag_Valor;
    private javax.swing.JComboBox<String> lst_Ag_Cliente;
    private javax.swing.JComboBox<String> lst_Ag_Servico;
    private javax.swing.JTable tbl_Agenda;
    private javax.swing.JTextField txt_Ag_Data;
    private javax.swing.JTextField txt_Ag_Hora;
    private javax.swing.JTextField txt_Ag_ID;
    private javax.swing.JTextArea txt_Ag_Obs;
    private javax.swing.JTextField txt_Ag_Valor;
    // End of variables declaration//GEN-END:variables
}
